server:
  port: 8888

spring:
  datasource:
    name: datasource
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/zoyo?serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      time-between-eviction-runs-millis: 300000
  redis:
    host: 127.0.0.1
    port: 8909
    password: 123456
    timeout: 10000 # 连接超时时间（毫秒）
    database: 0 # 数据库索引 默认0
    jedis:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
